name: ci

on: ['push', 'pull_request']

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16.10

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path ğŸ› 
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules ğŸ“¦
        uses: actions/cache@v3.0.1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Add codecov ğŸ“ˆğŸ’»
        run: yarn add codecov

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: yarn

      - name: Run linter ğŸ‘€
        run: yarn lint:fix

      - name: Run unit tests ğŸ§ª
        run: yarn jest --forceExit

      - name: Run e2e tests ğŸ§ª
        run: yarn jest --config ./test/jest-e2e.json --forceExit

      - name: Collect coverageğŸ“Š
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          yarn jest --forceExit --coverage
          yarn codecov
